<?php
/**
* @file
* Code for the Anchorage Helper module.
*/

/**
 * Implements hook_mail_alter().
 */
function anchorage_helper_mail_alter(&$message) {
  $debug = variable_get('anchorage_helper_debug', FALSE);
  if ($debug) {
    variable_set('anchorage_helper_pre', $message);
  }
  $message['headers']['Reply-To'] = $message['from'];
  $from = variable_get('anchorage_helper_ses_from', "anchorage-support@lists.stanford.edu");
  $message['from'] = $from;
  $message['headers']['From'] = $from;
  $message['headers']['Sender'] = $from;
  $message['headers']['Return-Path'] = $from;
  if ($debug) {
    variable_set('anchorage_helper_post', $message);
  }
}